s!\[IEEE\]!\\cite{IEEE}!g
s!\[JR\]!\\cite{JR}!g
s!\[K1\]!\\cite{K1}!g
s!\[K2\]!\\cite{K2}!g
s!\[A\]!\\cite{A}!g
s!\[P2\]!\\cite{P2}!g
s!\[ADST\]!\\cite{ADST}!g
s!\[CLLMR\]!\\cite{CLLMR}!g
s!\[G\]!\\cite{G}!g
s!\[GMM\]!\\cite{GMM}!g
s!\[GT\]!\\cite{GT}!g
s!\[LM\]!\\cite{LM}!g
s!\[L\]!\\cite{L}!g
s!\[Mi\]!\\cite{Mi}!g
s!\[GMT\]!\\cite{GMT}!g
